# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BSides Halifax Quarantine Edition"
email: "info@bsideshalifax.ca"
description: "BSides is a community-driven framework for building events for and by information security community members."
baseurl: ""
url: "https://bsideshalifax.ca"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-165605284-1"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "U2vM0e028DKxBzX3zvCNmR2ZQk31oXU5asShWbU3Oqg"

# Organizer Info
organizerName: "BSides Halifax"
organizerAlternateName: "Halifax BSides"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Cyber Security with passion."
organizerEmail: "info@bsideshalifax.ca"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://bsideshalifax.ca"

# Head
metaKeywords: "event, BSides, Halifax, Cyber, Security, infosec"
twitterAccount: "@HalifaxBSides"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4sponsorsUrl: "/assets/BSides_HFX_Sponsorship_Kit.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
 - {permalink: "/2020", text: "Last Years Event"}
bottomNavigationLinks:
- {link: "/assets/BSides_HFX_Sponsorship_Kit.pdf", text: "Become a sponsor"}

# Hero Block
heroImage: "halifax.jpg"
heroTitle: "BSides Halifax 2021"
eventDate: "Friday June 18, 2021"
typeoutTextValues: '"", "Virtual", "Quarantine Edition", "Stay The Blazes Home", "Donair Bonanza"'
typeoutFallback: "Virtual"
heroButtons:
- {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About BSides Halifax"
aboutBlock:
 - {
    title: "Conference",
    image: "conference.jpg",
    text: "
    <p>Hello from Halifax, the (EDIT: former) great oasis against coronavirus!</p>
    <p>We are again hosting our BSides Halifax infosec conference entirely online, and we'd really like you to attend.</p>
    <p>Hopefully, this will be your last ever pandemic conference, so it provides a great opportunity to share your lessons learned over the past 12 months. Did you learn how to manage your VPN more efficiently at high load, or discover a new MDM solution you think everyone should be using? We want to hear about it.</p>
    <p>The conference will be held on June 18th at https://BSidesHalifax.ca, and is accessible via laptop, tablet, phone, and whatever other sanitized devices have been made available to your quarantine facility.</p>
    <section>
    <h3>Call For Speakers</h3>
    <p>BSides Halifax 2021, this is going to be our year! Low case rates, vaccination proceeding swiftly, we're looking forward to finally getting together in per... wait, what's that?</p>
    <p>...I don't understand, why is it <a href=\"
    https://www.cs.cornell.edu/courses/cs3110/2020fa/textbook/data/variants.html\" target=\"blank\">OCaml's</a> fault we're online again this year?</p>
    <p>...Oh, DIFFERENT kind of variant. Got it.</p>
    <p>Yes, we are online again this year, and this one's going to be even better, because this time, we sort of know what we're doing!</p>
    <p>BSides Halifax 2021 is looking for a diverse group of speakers to present all manner of interesting things. Last year, we had speakers from all over Canada and America, on topics like reducing your cyber risk, threat hunting, and purple teaming, so if you don't live locally, or don't think your topic qualifies, submit a pitch anyway! You might get in.</p>

    <p><b>The submission process goes like this:</b></p>
    <ul>
      <li><p>Jeff, I don't know how the process goes. Write a list of steps, make it seem easy and fun.</p></li>
      <li><p>Send an email to <a href=\"mailto:info@bsideshalifax.ca\">info@bsideshalifax.ca</a> and be sure to tell us the title of your talk, a brief description (including length), where you are located, if you have any time constraints, what your favorite color is, and what your quest is.</p></li>
    </ul>
<br />
<h5>So if you are ready to make your (hopefully) last pandemic conference your best, send us a pitch. Why not start right now?</h5>
</section>
    "
}

# Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "4", specialCharacter: "+", info: "hours", detail: "of amazing talks"}
# - {count: "6", specialCharacter: "", info: "speakers", detail: "from across North America"}
# - {count: "24", specialCharacter: "", info: "hours", detail: "of CTF hacking goodness"}

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 3
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "All proceeds go to Feed Nova Scotia"
ticketsOffers:
-
 name: "General Admittance"
 price: "Donation ($13.37 is a great place to start)"
 priceCurrency: "CAD"
#   ticketsNumber: "150"
#   ribbon: "-5%"
 buyButtonLink: "https://www.eventbrite.ca/e/security-bsides-halifax-2021-virtual-tickets-154149175333"
 buyButtonText: "Buy Now"
 ticketContentList: ["Access to amazing talks", "Our everlasting love and admiration", "All proceeds go to Feed Nova Scotia"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=HalifaxBSides", icon: "twitter"}
 - {link: "https://discord.gg/aGzzj4B", icon: "site"}
 - {link: "https://github.com/bsideshalifax", icon: "github"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.securitybsides.com/w/page/12194156/FrontPage", text: "Security BSides", icon: "site"}
   - {link: "https://atlseccon.com", text: "Atlantic Security Conference", icon: "site"}
   - {link: "https://dc902.ca", text: "DEFCON Halifax", icon: "site"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@bsideshalifax.ca", text: "info@bsideshalifax.ca", icon: "email"}
 -
  title: "Code of Conduct"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: false

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
# aboutHackathonTitle: "CMD+CTRL"
# hackathonRows:
#    - {title: "", image: "hackathon-0.png", details: "<p>Stuck at home, but still want to test your skills in identifying web app vulnerabilities?  BSides Halifax and Security Innovation invite players to virtually compete in CMD+CTRL, a web application cyber range where players exploit their way through hundreds of vulnerabilities that lurk in business applications today.  Success means learning quickly that attack and defense is all about thinking on your feet.</p>
# <p>For each vulnerability you uncover, you are awarded points. Climb the interactive leaderboard for a chance to win fantastic prizes! CMD+CTRL is ideal for development teams to train and develop skills, but anyone involved in keeping your organization’s data secure can play - from developers and managers and even CISOs.</p>
# <p>All you need is your laptop and inner evil-doer!</p>
# <br />
# <p>Register early to reserve your spot and get a sneak peek at our cheat sheets and FAQs!</p>"}

# Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Hak5 Bash Bunny"}
#  - {title: "1st Place", image: "prize-1.jpg", info: "Hak5 WiFi Pineapple"}
#  - {title: "3rd Place", image: "prize-3.jpg", info: "Hak5 Packet Squirrle"}
